stages:
  - sonar-scanner
sonar-scanner:
 stage: sonar-scanner
 script:
   - source /etc/environment
   - sonar-scanner -Dsonar.projectKey=metagon-curator-business -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_KEY
 only:
   - master