exports.getMessage = () => {
return{
    "Welcome":"Howdy! Welcome Back",
    "Log":"Login",
    "Sign":"Signup",
    "Login_Mess": "Login to start working on your business profile page",
    "Remember":"Remember me",
    "No_Account":"Don't have an account?",
    "Forgot":"Forgot Password",
    "Reg":"Register to Get Started",
    "New_Reg":"Start working on your business profile page",
    "Conf_Code":"Enter the Confirmation code sent to your Registered Email",
    "Conf_Sign":"Confirm Sign up",
    "Conf_Err":"Confirmation code does not match",
    "Business":"Find Your Business",
    "Reg_Message": "By clicking register, I represent I have read, understand, and agree to the Postmates Privacy Policy and Terms of Service. This site is protected bt reCAPTCHA and google Privacy Policy and Terms of Service apply.",
    "Reset":"Reset Password",
    "Res_Message":"Enter the code sent to your Registered Email and also Enter your new password",
    "Pass_Err":"Password Does not match",
    "Log_Link":"Back to Login",
    "Submit":"Submit",
    "Email_Msg":"Enter the email address you registered with and we'll send you instruction to Reset your password",
    "Email_Err":"This Email is not Registered.",
    "Busi_Err":"The business you are trying to add is associated with an account. If you are the owner of the business and would like to reclaim the business for yourself, please send an email to support@metagon.com along with Proof",
    "phone_Err":"Phone number format should contain country code, Example:- +917599xxxxxx or +1257xxxx ",
    "Err":"You need to select your business to register.",
    "con":"Your password succesfully changed.",
    "pass_length":"Password does not conform to policy: Password not long enough",
    "title_error":"Length of title should be less then 50.",
    "description_error": "Length of description should be less then 200.",
    "date_err": "Start date should be less then end date."
}
}